# Libraries

```{r}
library(tidyverse)
```


# EDA

```{r}
games <- read_csv("data/games.csv")
```

```{r}
games %>%
  count(turns, victory_status, winner) %>% 
  ggplot(aes(turns, n)) +
  geom_col(aes(fill = winner)) +
  facet_grid(winner~victory_status, scale = "free")
```

```{r}
games %>% 
  count(opening_name, sort = TRUE) %>% View
```

```{r}
games %>%
  group_by(winner) %>%
  summarise(count = n(), .groups = 'drop') %>%
  mutate(count = count/sum(count)) %>% 
ggplot(., aes(reorder(winner, -count), count)) +
  geom_col() +
  geom_label(aes(label = paste0(round(count*100, 1), "%")), size = 5) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0,0.52)) +
  labs(title = "Result of games", x = "Colour of winner", 
       y = "Share of wins")
```

```{r}
games %>%
  mutate(avg_rating = (white_rating+black_rating)/2) %>%
  mutate(avg_rating = case_when(avg_rating < 1000 ~ "< 1000",
                                between(avg_rating, 1000, 1100)~ "1000-1000",
                                between(avg_rating, 1100, 1200)~ "1100-1200",
                                between(avg_rating, 1200, 1300)~ "1200-1300",
                                between(avg_rating, 1300, 1400)~ "1300-1400",
                                between(avg_rating, 1400, 1500)~ "1400-1500",
                                between(avg_rating, 1500, 1600)~ "1500-1600",
                                between(avg_rating, 1600, 1700)~ "1600-1700",
                                between(avg_rating, 1700, 1800)~ "1700-1800",
                                between(avg_rating, 1800, 1900)~ "1800-1900",
                                between(avg_rating, 1900, 2000)~ "1900-2000",
                                between(avg_rating, 2000, 2100)~ "2000-2100",
                                between(avg_rating, 2100, 2200)~ "2100-2200",
                                between(avg_rating, 2200, 2300)~ "2200-2300",
                                between(avg_rating, 2300, 2400)~ "2300-2400",
                                avg_rating > 2400 ~ "> 2400")) %>%
  group_by(avg_rating, winner) %>%
  summarise(count = n(), .groups = 'drop') %>%
ggplot(aes(avg_rating, count, fill = winner))+
  geom_bar(stat = "identity", position = "fill", alpha = 0.95, width = 1)+
  scale_fill_grey(start = 0.2, end = 0.9)+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  coord_flip()+
  scale_x_discrete(labels = c("< 1000","1000-1100","1100-1200","1200-1300","1300-1400",
                              "1400-1500","1500-1600","1600-1700","1700-1800","1800-1900",
                              "1900-2000","2000-2100","2100-2200","2200-2300","2300-2400","> 2400"))+
  labs(title = "Result of games", subtitle = "by lichess rating (average from 2 players)", x = "Average rating", fill = "Colour of winner: ",
       y = "Share of wins") +
  theme_classic() +
  theme(legend.position = "bottom") 
  
```

