---
output: html_document
editor_options: 
  chunk_output_type: console
---

Используемые библиотеки

```{r}
library(tidyverse)
library(readr)
library(lubridate)
```

Подготовка данных

```{r}
data_set <- read_delim("raw_data.csv", 
    ";", escape_double = FALSE, locale = locale(date_names = "ru", 
        encoding = "Windows-1251"), trim_ws = TRUE)
str(data_set)
View(data_set)

data_set <- data_set %>% 
  mutate(first_date = as.Date.character(date_zakryt, format = "%d.%m.%Y"),
         month = month(first_date, label = TRUE),
         week = week(first_date)) %>%
  filter(week != 26)
```

Недельная динамика использования мобильного приложения

```{r}
ggplot(data_set, aes(week, fill=source)) + 
  geom_bar(position = "fill") +
  scale_x_continuous(breaks = seq(27,46)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Неделя",
       y = "Процент закрытых заявок",
       fill = "Источник закрытия заявки",
       title = "Доля заявок, закрываемых из МП Сервисник",
       subtitle = "Данные по всем БЕ на 15 ноября 2019") +
  theme(legend.position="bottom")
#ggsave("Понедельный прогресс.png")
```

Категории заявок

```{r}
ggplot(data_set, aes(as.factor(kategor), fill=source)) + 
  geom_bar() + 
  facet_wrap(~month) +
  theme(legend.position="top") +
  labs(x = "Категории заявок",
       y = "Количество заявок",
       fill = "Источник закрытия заявки",
       title = "Какие категории закрываются",
       subtitle = "Данные по всем БЕ на 15 ноября 2019")
#ggsave("Какие категории закрывают.png")
```

Данные по БЕ 

```{r}
data_set %>% 
  mutate(be = fct_infreq(be)) %>%
  ggplot(aes(be, fill = source)) +
  geom_bar(position = "fill") + 
  coord_flip() +
  #facet_grid(~month) +
  theme(legend.position="bottom") + 
  facet_wrap(~month) +
    scale_y_continuous(labels = scales::percent)+
    labs(x = "Бизнес-единица",
       y = "Доля заявок",
       fill = "Источник закрытия заявки",
       title = "Закрытие заявок по Бизнес-единицам",
       subtitle = "Помесячные данные")
#ggsave("Помесячные данные.png")

data_set %>% 
  filter(month == "окт") %>% 
  mutate(be = fct_infreq(be)) %>%
  ggplot(aes(be, fill = source)) +
  geom_bar(position = "fill") + 
  coord_flip() +
  #facet_grid(~month) +
  theme(legend.position="bottom") + 
  scale_y_continuous(labels = scales::percent)+
    labs(x = "Бизнес-единица",
       y = "Доля заявок",
       fill = "Источник закрытия заявки",
       title = "Закрытие заявок по Бизнес-единицам",
       subtitle = "Данные за октябрь")
#ggsave("Октябрь.png")



data_set %>% 
  filter(month == "окт") %>%
  mutate(be = as.factor(be)) %>% 
  group_by(be, source) %>% 
  summarise(count = n()) %>% 
  ungroup() %>%
  pivot_wider(names_from = source, 
              values_from = count) %>% 
  mutate(percent = (Сервисник / Тринити)) %>%
  pivot_longer(cols = contains("ни"),
               names_to = "source", 
               values_to = "count") %>%
  mutate(be = fct_reorder(be, -percent)) %>% 
  ggplot(mapping = aes(x = be, y = count, fill = source)) +
  geom_col(position = "fill") +
  coord_flip() +
    theme(legend.position="top") + 
  scale_y_continuous(labels = scales::percent)+
    labs(x = "Бизнес-единица",
       y = "Доля заявок",
       fill = "Источник закрытия заявки",
       title = "Закрытие заявок по Бизнес-единицам",
       subtitle = "Данные за октябрь")
#ggsave("Октябрь.png")
```

Три худших БЕ, с процентом закрытия заявок из Тринити больше 50%

```{r}
data_set %>% 
  filter(be == "ННВ", week >= 40,
         !is.na(ispolnitel)) %>%
  mutate(ispolnitel = fct_infreq(ispolnitel)) %>%
  ggplot(aes(ispolnitel, fill = source)) +
  geom_bar() + 
  coord_flip() +
  labs(x = "Кто закрывает заявку",
       y = "Заявки",
       fill = "Источник закрытия заявки",
       title = "Закрытие заявок в БЕ Нижний Новгород",
       subtitle = "Данные с 1-го октября по 15-ое ноября 2019") +
  theme(legend.position="bottom")
#ggsave("Нижний Новгород.png")

data_set %>% 
  filter(be == "ОРН", week >= 40,
         !is.na(ispolnitel)) %>%
  mutate(ispolnitel = fct_infreq(ispolnitel)) %>%
  ggplot(aes(ispolnitel, fill = source)) +
  geom_bar() + 
  coord_flip() +
  labs(x = "Кто закрывает заявку",
       y = "Заявки",
       fill = "Источник закрытия заявки",
       title = "Закрытие заявок в БЕ Оренбург",
       subtitle = "Данные с 1-го октября по 15-ое ноября 2019") +
  theme(legend.position="bottom")
ggsave("Оренбург.png")

data_set %>% 
  filter(be == "ЕКТ", week >= 40,
         !is.na(ispolnitel)) %>%
  mutate(ispolnitel = fct_infreq(ispolnitel)) %>%
  ggplot(aes(ispolnitel, fill = source)) +
  geom_bar() + 
  coord_flip() +
  labs(x = "Кто закрывает заявку",
       y = "Заявки",
       fill = "Источник закрытия заявки",
       title = "Закрытие заявок в БЕ Екатеринбург",
       subtitle = "Данные с 1-го октября по 15-ое ноября 2019") +
  theme(legend.position="bottom")
ggsave("екатеринбург.png")

```
