---
title: "franchise"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r, include=FALSE}
library(tidyverse)
library(lubridate)
theme_set(theme_light())
library(glue)
```

[Ссылка на описание данных](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-07-02)

# Получение данных

```{r}
media_franchises <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-02/media_franchises.csv")
# revenue = доход в миллиардах
```

# Обработка данных

```{r}
media_franchises %>% 
  count(franchise, sort = TRUE)

franchises <- media_franchises %>% 
  group_by(revenue, franchise, original_media, year_created, creators, owners) %>% 
  summarise(categories = n(),
            total_revenue = sum(revenue),
            most_profitable = revenue_category[which.max(revenue)], .groups = "drop")
```


## Уровень франшиз

Какие франшизы были самыми большими
```{r, fig.width=9, fig.height=7}
franchises %>% 
  arrange(desc(revenue)) %>% 
  head(16) %>% 
  mutate(franchise = fct_reorder(franchise, revenue)) %>% 
  ggplot(aes(franchise, revenue)) +
  geom_col() +
  coord_flip() +
  labs(title = "Какие франшизы принесли больше всего денег, с момента их создания") +
  theme(legend.position = "bottom")
```

```{r, fig.width=9, fig.height=7}
media_franchises %>% 
  semi_join(franchises %>% top_n(16, total_revenue), by = "franchise") %>% 
  mutate(franchise = glue("{ franchise } ({ year_created})")) %>% 
   mutate(franchise = fct_reorder(franchise, revenue, sum),
          revenue_category = fct_reorder(revenue_category, revenue, sum)) %>% 
  ggplot(aes(franchise, revenue, fill = revenue_category)) +
  scale_y_continuous(labels = scales::dollar) +
  geom_col() +
  coord_flip() +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = "Какие франшизы принесли больше всего денег, с момента их создания",
       fill = "Категория",
       x = "",
       y = "Миллиарды долларов") +
  theme(legend.position = "bottom")
```

```{r, fig.width=9, fig.height=7}
franchises %>% 
  group_by(owners) %>% 
  filter(revenue == max(revenue)) %>% 
  ungroup() %>% 
  mutate(franchise = glue("{ franchise } ({ year_created})")) %>% 
  mutate(franchise = fct_reorder(franchise, total_revenue),
         owners = fct_reorder(owners, total_revenue, sum)) %>% 
  filter(revenue >= 20) %>% 
  ggplot(aes(owners, revenue)) +
  geom_col(aes(fill = franchise)) +
  geom_text(aes(label = franchise)) +
  coord_flip() +
  theme(legend.position = "none") +
    labs(title = "Обладатели самых прибыльных франшиз",
         subtitle = "c доходом больше 20 млрд.",
       fill = "категория франшизы",
       x = "",
       y = "Миллиарды долларов")
```

```{r, fig.width=9, fig.height=7}
media_franchises %>% 
  group_by(owners) %>% 
  filter(n_distinct(franchise) > 2) %>% 
  ungroup() %>% 
  mutate(franchise = glue("{ franchise } ({ year_created})")) %>% 
  mutate(franchise = fct_reorder(franchise, revenue, sum),
         owners = fct_reorder(owners, -revenue, sum),
         revenue_category = fct_reorder(revenue_category, revenue, sum)) %>%
  ggplot(aes(franchise, revenue, fill = revenue_category)) +
  geom_col() +
  facet_wrap(~owners, scales = "free_y") +
  coord_flip() +
  scale_y_continuous(labels = scales::dollar) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  labs(title = " Какие компании обладают по меньшей мере тремя франшизами",
       fill = "категория франшизы",
       x = "",
       y = "Миллиарды долларов")
```

Посмотрим в разрезе года основания
```{r, fig.width=9, fig.height=7}
franchises %>% 
  mutate(label = ifelse(total_revenue < 30, NA_character_, franchise)) %>% 
  ggplot(aes(year_created, total_revenue)) +
  geom_point(aes(size = total_revenue, color = original_media)) +
  geom_text(aes(label = label), hjust = -0.1, vjust = -1) +
  theme(legend.position = "bottom")
```


